(define demo-action #f)
(define demo-path #f)
(define demo-data #f)

(define (demo-error message)
  (error (string-append "demo: " message)))

(let scan ((index 0))
  (when (< index (vector-length argv))
    (let ((option (ref argv index)))
      (cond
        ((or (string=? option "--record-demo") (string=? option "--play-demo"))
         (when demo-action
           (demo-error "choose one --record-demo or --play-demo file"))
         (when (= (+ index 1) (vector-length argv))
           (demo-error (string-append option " requires a file")))
         (set! demo-path (ref argv (+ index 1)))
         (when (or (= (string-length demo-path) 0)
                   (and (>= (string-length demo-path) 2)
                        (string=? (substring demo-path 0 2) "--")))
           (demo-error (string-append option " requires a file")))
         (set! demo-action (if (string=? option "--record-demo") 'record 'play))
         (set! demo-session #t)
         (scan (+ index 2)))
        ((string=? option "--headless")
         (when demo-headless (demo-error "--headless specified twice"))
         (set! demo-headless #t)
         (scan (+ index 1)))
        ((string=? option "--datadir") (scan (+ index 2)))
        (else (scan (+ index 1)))))))

(when (and demo-headless (not (eq? demo-action 'play)))
  (demo-error "--headless requires --play-demo"))

(when (eq? demo-action 'play)
  (let ((port (open-input-file/maybe demo-path)))
    (unless port (demo-error "cannot open playback file"))
    (set! demo-data (read-bytes/all port))
    (close-input-port port))
  (unless (and (>= (bytevector-length demo-data) 19)
               (= (ref demo-data 0) 87) (= (ref demo-data 1) 79)
               (= (ref demo-data 2) 76) (= (ref demo-data 3) 70)
               (= (ref demo-data 4) 1) (<= (ref demo-data 5) 1)
               (= (ref demo-data 6) 19) (= (ref demo-data 7) gd_hard)
               (= (bytevector-length demo-data) (+ 16 (* 3 (readu32 demo-data 8)))))
    (demo-error "invalid or unsupported demo file"))
  (when (and (argument? "--plus") (= (ref demo-data 5) 0))
    (demo-error "this recording has --plus disabled"))
  (let controls ((offset 16))
    (when (< offset (bytevector-length demo-data))
      (when (or (> (abs (demo-byte (ref demo-data (+ offset 1)))) 100)
                (> (abs (demo-byte (ref demo-data (+ offset 2)))) 100))
        (demo-error "movement outside the recorded control range"))
      (controls (+ offset 3)))))
