(define demo-frames 0)

(define (demo-checksum)
  (define (mix hash value)
    (modulo (+ (* hash 65599) value) 4294967296))
  (define (bytes buffer hash)
    (let loop ((index 0) (hash hash))
      (if (= index (bytevector-length buffer))
          hash
          (loop (+ index 1) (mix hash (ref buffer index))))))
  (let fields ((values (list player-x player-y player-angle health ammo score rndindex TimeCount
                            killcount treasurecount secretcount))
               (hash (bytes curpal (bytes framebuffer 0))))
    (if (null? values)
        hash
        (let ((text (number->string (car values))))
          (let chars ((index 0) (hash hash))
            (if (= index (string-length text))
                (fields (cdr values) (mix hash 0))
                (chars (+ index 1) (mix hash (char->integer (ref text index))))))))))

(define (demo-put32! buffer offset value)
  (setu16! buffer offset (bitwise-and value 65535))
  (setu16! buffer (+ offset 2) (arithmetic-shift value -16)))

(define (demo-save checksum)
  (when (= demo-frames 0) (demo-error "recording is empty"))
  (let ((header (bytevector 87 79 76 70 1 (if plus-available 1 0) 19 gd_hard 0 0 0 0 0 0 0 0))
        (port (open-output-file demo-path)))
    (demo-put32! header 8 demo-frames)
    (demo-put32! header 12 checksum)
    (write-bytes header port)
    (write-bytes (bytevector-copy demo-buffer 4 demo-pointer) port)
    (close-output-port port)))

(define (run-demo)
  (NewGame gd_hard 0)
  (set! ingame #t)
  (set! mouseenabled (and (eq? demo-action 'record) MousePresent (not demo-headless)))
  (if (eq? demo-action 'record)
      (begin
        (StartDemoRecord 0)
        (display "Recording level 1 without sound. Press Escape to save and exit.\n"))
      (begin
        (set! demo-buffer demo-data)
        (set! demo-pointer 16)
        (set! demo-end (bytevector-length demo-data))
        (set! demoplayback #t)))
  (set! vl-vbl #f)
  (DrawPlayScreen)
  (SetupGameLevel)
  (PM_CheckMainMem)
  (VL_SetPalette gamepal)
  (set! screenfaded #f)
  (set! fizzlein #f)
  (set! demo-lasttimecount 0)
  (set! demo-deadline (time-monotonic))
  (let ((started (time-monotonic)))
    (let loop ()
      (when (and (= playstate ex_stillplaying)
                 (if demoplayback
                     (< demo-pointer demo-end)
                     (not (ref Keyboard sc_Escape))))
        (PlayLoop)
        (set! demo-frames (+ demo-frames 1))
        (unless demo-headless (IN_Yield))
        (loop)))
    (let ((elapsed (* 1000 (- (time-monotonic) started)))
          (checksum (demo-checksum)))
      (display (string-append "demo: frames=" (number->string demo-frames)
                              " ticks=" (number->string (* demo-frames DEMOTICS))
                              " ms=" (number->string elapsed)
                              (if demo-headless
                                  (string-append " fps="
                                    (if (> elapsed 0)
                                        (number->string (/ (round (/ (* 10000 demo-frames) elapsed)) 10))
                                        "n/a"))
                                  "")
                              " checksum=" (number->string checksum) "\n"))
      (when demorecord (demo-save checksum))))
  (set! demorecord #f)
  (set! demoplayback #f))
