(define plus-enabled
  (if (eq? demo-action 'play)
      (= (ref demo-data 5) 1)
      (let scan ((index 0))
        (if (= index (vector-length argv))
            #f
            (or (string=? (ref argv index) "--plus") (scan (+ index 1)))))))

(define PLUS_LIGHT_RADIUS 6)
(define PLUS_LIGHT_LEVELS 8)
(define PLUS_EMISSIVE_LUMA 48)
(define PLUS_FLASH_LEVELS 32)
(define PLUS_FLASH_TICS 8)
(define PLUS_FLASH_COUNT 4)
(define PLUS_AO_RANGE 1)
(define PLUS_AO_DEPTH 48)
(define PLUS_SHADOW_DEPTH 48)

(define plus-boundaries (make-vector (vector-length wallheight) 0))
(define plus-shades (make-vector 20 0))
(define plus-emissive (make-bytevector 256 0))
(define plus-luma (make-bytevector 256 0))
(define plus-feet (make-vector (+ SPR_GRD_SHOOT3 1) #f))
(define plus-lightmap (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define plus-flashmaps
  (vector (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)))
(define plus-flash-starts (make-vector PLUS_FLASH_COUNT -1))
(define plus-flash-next 0)

(define (plus-color color level)
  (if plus-enabled (ref (ref plus-shades (+ level 4)) color) color))

(define (plus-shade level16)
  (- (truncate (/ (+ level16 72) 16)) 4))

(define (plus-sprite-color color level16 emission)
  (if (and (> emission 0) (= (ref plus-emissive color) 1))
      (if (= emission 1) (plus-color color (plus-shade (truncate (/ level16 2)))) color)
      (plus-color color (plus-shade level16))))

(define (plus-distance-level extent range)
  (if plus-enabled
      (let ((distance (- range (min extent range))))
        (truncate (/ (* 240 distance distance distance distance) (* range range range range))))
      0))

(define (plus-light-index tilex tiley)
  (+ (* tiley MAPSIZE) tilex))

(define (plus-light-level level tilex tiley)
  (if plus-enabled
      (let* ((spot (plus-light-index tilex tiley))
             (flash (let slots ((slot 0) (brightest 0))
                      (if (= slot PLUS_FLASH_COUNT)
                          brightest
                          (let* ((remaining
                                  (if (> (ref plus-flash-starts slot) TimeCount)
                                      0
                                      (max 0 (- PLUS_FLASH_TICS (- TimeCount (ref plus-flash-starts slot))))))
                                 (level (truncate
                                         (/ (* (ref (ref plus-flashmaps slot) spot) remaining)
                                            PLUS_FLASH_TICS))))
                            (slots (+ slot 1) (max brightest level))))))
             (dark (truncate (/ (* level (- 15 (ref plus-lightmap spot))) 15)))
             (bright (if (= flash 0)
                         0
                         (min 4 (max 1 (truncate (/ (* 4 flash) PLUS_FLASH_LEVELS)))))))
        (max -64 (- dark (* 16 bright))))
      0))

(define (plus-light-emission shape)
  (cond ((= shape (+ SPR_STAT_0 3)) 1)
        ((or (= shape (+ SPR_STAT_0 4)) (= shape (+ SPR_STAT_0 14))) 2)
        (else 0)))

(define (plus-light-shape? shape)
  (> (plus-light-emission shape) 0))

(define (plus-build-table factor)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (let* ((red (min 63 (truncate (/ (* (ref gamepal (* color 3)) factor) 15))))
               (green (min 63 (truncate (/ (* (ref gamepal (+ (* color 3) 1)) factor) 15))))
               (blue (min 63 (truncate (/ (* (ref gamepal (+ (* color 3) 2)) factor) 15))))
               (best (let search ((index 0) (bestdist -1) (bestindex 0))
                       (if (= index 256)
                           bestindex
                           (let ((dred (- red (ref gamepal (* index 3))))
                                 (dgreen (- green (ref gamepal (+ (* index 3) 1))))
                                 (dblue (- blue (ref gamepal (+ (* index 3) 2)))))
                             (let ((dist (+ (* dred dred) (* dgreen dgreen) (* dblue dblue))))
                               (if (or (< bestdist 0) (< dist bestdist))
                                   (search (+ index 1) dist index)
                                   (search (+ index 1) bestdist bestindex))))))))
          (setf! table color best))
        (colors (+ color 1))))
    table))

(define (plus-build-shades)
  (let ((identity (make-bytevector 256 0)))
    (let loop ((index 0))
      (when (< index 256)
        (let ((luma (truncate (/ (+ (* 54 (ref gamepal (* index 3)))
                                      (* 183 (ref gamepal (+ (* index 3) 1)))
                                      (* 19 (ref gamepal (+ (* index 3) 2))))
                                   256))))
          (setf! identity index index)
          (setf! plus-luma index luma)
          (setf! plus-emissive index (if (>= luma PLUS_EMISSIVE_LUMA) 1 0)))
        (loop (+ index 1))))
    (setf! plus-shades 4 identity))
  (let bright ((level 1))
    (when (<= level 4)
      (setf! plus-shades (- 4 level) (plus-build-table (+ 15 (* level 2))))
      (bright (+ level 1))))
  (let dark ((level 1))
    (when (< level 16)
      (setf! plus-shades (+ level 4) (plus-build-table (- 15 level)))
      (dark (+ level 1)))))

(define (plus-light-passable? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE) (< (tileat tilex tiley) 128)))

(define (plus-ao level16 distance)
  (if (and plus-enabled (>= distance 0) (< distance PLUS_AO_RANGE))
      (min 240 (+ level16 PLUS_AO_DEPTH))
      level16))

(define (plus-spread-light target lightx lighty radius levels)
  (let ((queue (make-vector (* MAPSIZE MAPSIZE) 0))
        (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
        (tail 1))
    (setf! queue 0 (plus-light-index lightx lighty))
    (setf! distance (plus-light-index lightx lighty) 0)
    (let flood ((head 0))
      (when (< head tail)
        (let* ((spot (ref queue head))
               (tilex (remainder spot MAPSIZE))
               (tiley (quotient spot MAPSIZE))
               (steps (ref distance spot))
               (level (- levels (truncate (/ (* levels steps) radius)))))
          (when (> level (ref target spot))
            (setf! target spot level))
          (when (< steps radius)
            (let visit ((neighbors (list (tuple (- tilex 1) tiley) (tuple (+ tilex 1) tiley)
                                          (tuple tilex (- tiley 1)) (tuple tilex (+ tiley 1)))))
              (when (pair? neighbors)
                (let* ((neighbor (car neighbors))
                       (nextx (ref neighbor 0))
                       (nexty (ref neighbor 1)))
                  (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE))
                    (let ((next (plus-light-index nextx nexty)))
                      (let ((nextlevel (- levels (truncate (/ (* levels (+ steps 1)) radius)))))
                        (when (> nextlevel (ref target next))
                          (setf! target next nextlevel)))
                      (when (and (< (tileat nextx nexty) 128)
                                 (> (ref distance next) (+ steps 1)))
                        (setf! distance next (+ steps 1))
                        (setf! queue tail next)
                        (set! tail (+ tail 1)))))
                  (visit (cdr neighbors)))))
          (flood (+ head 1))))))))

(define (plus-build-lights)
  (let clear ((index 0))
    (when (< index (* MAPSIZE MAPSIZE))
      (setf! plus-lightmap index 0)
      (clear (+ index 1))))
  (let lights ((index 0))
    (when (< index statcount)
      (when (plus-light-shape? (ref stat-shape index))
        (plus-spread-light plus-lightmap (ref stat-tilex index) (ref stat-tiley index)
                           PLUS_LIGHT_RADIUS PLUS_LIGHT_LEVELS))
      (lights (+ index 1)))))

(define (plus-flash-at tilex tiley)
  (when plus-enabled
    (let ((flashmap (ref plus-flashmaps plus-flash-next))
          (queue (make-vector (* MAPSIZE MAPSIZE) 0))
          (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
          (tail 1))
      (let clear ((index 0))
        (when (< index (* MAPSIZE MAPSIZE))
          (setf! flashmap index 0)
          (clear (+ index 1))))
      (setf! queue 0 (plus-light-index tilex tiley))
      (setf! distance (plus-light-index tilex tiley) 0)
      (let flood ((head 0) (maxd 0))
        (if (< head tail)
            (let* ((spot (ref queue head))
                   (tx (remainder spot MAPSIZE))
                   (ty (quotient spot MAPSIZE))
                   (steps (ref distance spot)))
              (let visit ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                           (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                (when (pair? neighbors)
                  (let* ((neighbor (car neighbors))
                         (nextx (ref neighbor 0))
                         (nexty (ref neighbor 1)))
                    (when (plus-light-passable? nextx nexty)
                      (let ((next (plus-light-index nextx nexty)))
                        (when (> (ref distance next) (+ steps 1))
                          (setf! distance next (+ steps 1))
                          (setf! queue tail next)
                          (set! tail (+ tail 1)))))
                    (visit (cdr neighbors)))))
              (flood (+ head 1) (max maxd steps)))
            (let stamp ((index 0))
              (if (< index tail)
                  (let* ((spot (ref queue index))
                         (tx (remainder spot MAPSIZE))
                         (ty (quotient spot MAPSIZE))
                         (steps (ref distance spot))
                         (level (if (= maxd 0)
                                    PLUS_FLASH_LEVELS
                                    (max 1 (- PLUS_FLASH_LEVELS
                                              (truncate (/ (* PLUS_FLASH_LEVELS steps) maxd)))))))
                    (setf! flashmap spot level)
                    (let walls ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                                 (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                      (when (pair? neighbors)
                        (let* ((neighbor (car neighbors))
                               (nextx (ref neighbor 0))
                               (nexty (ref neighbor 1)))
                          (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE)
                                     (>= (tileat nextx nexty) 128))
                            (let ((next (plus-light-index nextx nexty)))
                              (when (> level (ref flashmap next))
                                (setf! flashmap next level)))))
                        (walls (cdr neighbors))))
                    (stamp (+ index 1)))
                  (begin
                    (setf! plus-flash-starts plus-flash-next TimeCount)
                    (set! plus-flash-next (remainder (+ plus-flash-next 1) PLUS_FLASH_COUNT))))))))))

(define (plus-guard? shape)
  (or (and (>= shape SPR_GRD_S_1) (< shape SPR_GRD_DIE_1))
      (= shape SPR_GRD_PAIN_2)
      (and (>= shape SPR_GRD_SHOOT1) (<= shape SPR_GRD_SHOOT3))))

(define (plus-build-feet)
  (let shapes ((shape SPR_GRD_S_1))
    (when (<= shape SPR_GRD_SHOOT3)
      (when (plus-guard? shape)
        (let* ((page (PM_GetPage (+ PMSpriteStart shape)))
               (left (readu16 page 0))
               (right (readu16 page 2))
               (first 64)
               (last -1))
          (let columns ((column left))
            (when (<= column right)
              (let posts ((offset (readu16 page (+ 4 (* (- column left) 2)))))
                (let ((end (readu16 page offset)))
                  (when (> end 0)
                    (when (and (> end 120) (< (readu16 page (+ offset 4)) 128))
                      (set! first (min first column))
                      (set! last (max last column)))
                    (posts (+ offset 6)))))
              (columns (+ column 1))))
          (when (<= first last)
            (setf! plus-feet shape (tuple first (+ last 1))))))
      (shapes (+ shape 1)))))

(define (plus-shadow index feet)
  (let* ((height (ref vis-height index))
         (scale (truncate (/ height 8))))
    (when (and (> scale 0) (<= scale maxscale))
      (let* ((rows (* scale 2))
             (center (ref vis-x index))
             (left (+ center (- (truncate (/ (* (- (ref feet 0) 1) rows) 64)) scale)))
             (right (+ center (- (truncate (/ (* (+ (ref feet 1) 1) rows) 64)) scale)))
             (bottom (+ (truncate (/ (- viewheight rows) 2)) rows -1))
             (depth (max 1 (truncate (/ rows 64))))
             (level (plus-light-level 0 (ref vis-tilex index) (ref vis-tiley index)))
             (color (plus-color FLOOR (plus-shade (min 240 (+ level PLUS_SHADOW_DEPTH)))))
             (luma (ref plus-luma color)))
        (let scan ((row (max (arithmetic-shift viewheight -1) (- bottom depth))))
          (when (and (< row (+ bottom depth)) (< row viewheight))
            (let* ((inset (truncate (/ (* (- right left) (abs (- row bottom))) (* depth 4))))
                   (end (min viewwidth (- right inset))))
              (let columns ((column (max 0 (+ left inset))))
                (when (< column end)
                  (when (and (< (ref wallheight column) height)
                             (>= row (+ (arithmetic-shift viewheight -1) (ref plus-boundaries column))))
                    (let ((pixel (+ (* (+ viewtop row) screenwidth) viewleft column)))
                      (when (> (ref plus-luma (ref framebuffer pixel)) luma)
                        (setf! framebuffer pixel color))))
                  (columns (+ column 1)))))
            (scan (+ row 1))))))))

(define (plus-draw-shadows)
  (when plus-enabled
    (let sprites ((index 0))
      (when (< index viscount)
        (let ((shape (ref vis-shape index)))
          (when (plus-guard? shape)
            (let ((feet (ref plus-feet shape)))
              (when feet (plus-shadow index feet)))))
        (sprites (+ index 1))))))

(define (plus-palette-loaded)
  (when plus-enabled (plus-build-shades)))

(define (plus-startup)
  (when plus-enabled (plus-build-feet)))

(define (plus-level-loaded)
  (when plus-enabled
    (let reset ((slot 0))
      (when (< slot PLUS_FLASH_COUNT)
        (let ((flashmap (ref plus-flashmaps slot)))
          (let clear ((index 0))
            (when (< index (* MAPSIZE MAPSIZE))
              (setf! flashmap index 0)
              (clear (+ index 1)))))
        (setf! plus-flash-starts slot -1)
        (reset (+ slot 1))))
    (set! plus-flash-next 0)
    (plus-build-lights)))

(define (plus-draw-planes)
  (when plus-enabled
    (let ((halfh (arithmetic-shift viewheight -1))
          (ceilcolor (ceiling-color))
          (centercol (arithmetic-shift viewwidth -1)))
      (let columns ((x 0))
        (when (< x viewwidth)
          (setf! plus-boundaries x (arithmetic-shift (scale-rows (ref wallheight x)) -1))
          (columns (+ x 1))))

      (let rows ((h 1))
        (when (< h halfh)
          (let* ((level 0)
                 (length (truncate (/ (* 32768 scale) h)))
                 (xstep (truncate (/ (* viewsin 2) h)))
                 (ystep (truncate (/ (* viewcos 2) h)))
                 (startx (+ viewx (FixedMul length viewcos)))
                 (starty (- viewy (FixedMul length viewsin)))
                 (top (- halfh 1 h))
                 (bottom (+ halfh h)))
            (when (and (>= top 0) (< bottom viewheight))
              (let columns ((x 0))
                (when (< x viewwidth)
                  (let ((distance (- h (ref plus-boundaries x))))
                    (when (>= distance 0)
                      (let* ((prestep (- centercol x))
                             (xf (- startx (arithmetic-shift (* xstep prestep) -2)))
                             (yf (- starty (arithmetic-shift (* ystep prestep) -2)))
                             (lit (plus-ao (plus-light-level level
                                                             (bitwise-and (arithmetic-shift xf -16) 63)
                                                             (bitwise-and (arithmetic-shift yf -16) 63))
                                           distance))
                             (shade (plus-shade lit)))
                        (setf! framebuffer (+ (* (+ viewtop top) screenwidth) viewleft x)
                               (plus-color ceilcolor shade))
                        (setf! framebuffer (+ (* (+ viewtop bottom) screenwidth) viewleft x)
                               (plus-color FLOOR shade)))))
                  (columns (+ x 1))))))
          (rows (+ h 1)))))))
