(define plus-enabled
  (if (eq? demo-action 'play)
      (= (ref demo-data 5) 1)
      (let scan ((index 0))
        (if (= index (vector-length argv))
            #f
            (or (string=? (ref argv index) "--plus") (scan (+ index 1)))))))

(define plus-turn-speed 62.5)
(define plus-walk-speed 52.5)

(let scan ((index 0))
  (when (< index (vector-length argv))
    (let ((option (ref argv index)))
      (if (or (string=? option "--turn-speed") (string=? option "--walk-speed"))
          (begin
            (unless plus-enabled
              (error (string-append option " requires --plus")))
            (when (eq? demo-action 'play)
              (error (string-append option " cannot change recorded movement")))
            (let ((speed (and (< (+ index 1) (vector-length argv))
                              (string->number (ref argv (+ index 1))))))
              (unless (and speed (> speed 0) (<= speed 100))
                (error (string-append option " requires a number greater than 0 and at most 100")))
              (if (string=? option "--turn-speed")
                  (set! plus-turn-speed speed)
                  (set! plus-walk-speed speed)))
            (scan (+ index 2)))
          (scan (+ index 1))))))

(define PLUS_LIGHT_RADIUS 6)
(define PLUS_LIGHT_LEVELS 8)
(define PLUS_EMISSIVE_LUMA 48)
(define PLUS_FLASH_LEVELS 32)
(define PLUS_FLASH_TICS 8)
(define PLUS_FLASH_COUNT 4)
(define PLUS_AO_RANGE 3)
(define PLUS_AO_WIDTH (* (/ TILEGLOBAL 8) (/ 3 5)))
(define PLUS_AO_STEP 4)
(define PLUS_CORNER_STEPS 2)
(define plus-ao-enabled #t)
(define plus-ao-debug #f)
(define plus-ao-debug-colors #(#(0 0 63) #(63 63 0) #(63 0 63)))
(define plus-ao-key #f)
(define plus-ao-shades (make-vector PLUS_AO_RANGE 0))
(define plus-corners-enabled #t)
(define plus-corners-key #f)
(define plus-corner-shades (make-vector PLUS_AO_RANGE 0))
(define plus-contact-enabled #t)
(define plus-contact-key #f)
(define plus-palette-slots #(5 80 81 82 83 84 85 86 87 166 167 168 169 170 176 177 178 181 255))
(define PLUS_SHADOW_DEPTH 48)

(define plus-boundaries (make-vector (vector-length wallheight) 0))
(define plus-planex (make-vector (vector-length wallheight) 0))
(define plus-planey (make-vector (vector-length wallheight) 0))
(define plus-shades
  (let ((identity (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (setf! identity color color)
        (colors (+ color 1))))
    (make-vector 20 identity)))
(define plus-emissive (make-bytevector 256 0))
(define plus-luma (make-bytevector 256 0))
(define plus-feet (make-vector (+ SPR_GRD_SHOOT3 1) #f))
(define plus-lightmap (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define plus-flashmaps
  (vector (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)))
(define plus-flash-starts (make-vector PLUS_FLASH_COUNT -1))
(define plus-flash-next 0)

(define (plus-color color level)
  (if plus-enabled (ref (ref plus-shades (+ level 4)) color) color))

(define (plus-shade level16)
  (- (truncate (/ (+ level16 72) 16)) 4))

(define (plus-sprite-color color level16 emission)
  (if (and (> emission 0) (= (ref plus-emissive color) 1))
      (if (= emission 1) (plus-color color (plus-shade (truncate (/ level16 2)))) color)
      (plus-color color (plus-shade level16))))

(define (plus-distance-level extent range)
  (if plus-enabled
      (let ((distance (- range (min extent range))))
        (truncate (/ (* 240 distance distance distance distance) (* range range range range))))
      0))

(define (plus-light-index tilex tiley)
  (+ (* tiley MAPSIZE) tilex))

(define (plus-light-level level tilex tiley)
  (if plus-enabled
      (let* ((spot (plus-light-index tilex tiley))
             (flash (let slots ((slot 0) (brightest 0))
                      (if (= slot PLUS_FLASH_COUNT)
                          brightest
                          (let* ((remaining
                                  (if (> (ref plus-flash-starts slot) TimeCount)
                                      0
                                      (max 0 (- PLUS_FLASH_TICS (- TimeCount (ref plus-flash-starts slot))))))
                                 (level (truncate
                                         (/ (* (ref (ref plus-flashmaps slot) spot) remaining)
                                            PLUS_FLASH_TICS))))
                            (slots (+ slot 1) (max brightest level))))))
             (dark (truncate (/ (* level (- 15 (ref plus-lightmap spot))) 15)))
             (bright (if (= flash 0)
                         0
                         (min 4 (max 1 (truncate (/ (* 4 flash) PLUS_FLASH_LEVELS)))))))
        (max -64 (- dark (* 16 bright))))
      0))

(define (plus-light-emission shape)
  (cond ((= shape (+ SPR_STAT_0 3)) 1)
        ((or (= shape (+ SPR_STAT_0 4)) (= shape (+ SPR_STAT_0 14))) 2)
        (else 0)))

(define (plus-light-shape? shape)
  (> (plus-light-emission shape) 0))

(define (plus-build-table factor)
  (plus-build-colors factor truncate))

(define (plus-build-colors factor quantize)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (let* ((red (min 63 (quantize (/ (* (ref gamepal (* color 3)) factor) 15))))
               (green (min 63 (quantize (/ (* (ref gamepal (+ (* color 3) 1)) factor) 15))))
               (blue (min 63 (quantize (/ (* (ref gamepal (+ (* color 3) 2)) factor) 15))))
               (best (let search ((index 0) (bestdist -1) (bestindex 0))
                       (if (= index 256)
                           bestindex
                           (let ((dred (- red (ref gamepal (* index 3))))
                                 (dgreen (- green (ref gamepal (+ (* index 3) 1))))
                                 (dblue (- blue (ref gamepal (+ (* index 3) 2)))))
                             (let ((dist (+ (* dred dred) (* dgreen dgreen) (* dblue dblue))))
                               (if (or (< bestdist 0) (< dist bestdist))
                                   (search (+ index 1) dist index)
                                   (search (+ index 1) bestdist bestindex))))))))
          (setf! table color best))
        (colors (+ color 1))))
    table))

(define (plus-linear channel)
  (let ((value (/ channel 63)))
    (if (<= value 0.04045)
        (/ value 12.92)
        (expt (/ (+ value 0.055) 1.055) 2.4))))

(define (plus-channel value)
  (round (* 63 (if (<= value 0.0031308)
                  (* value 12.92)
                  (- (* 1.055 (expt value (/ 1 2.4))) 0.055)))))

(define (plus-ao-target color light row)
  (let* ((red (plus-linear (min 63 (* (ref gamepal (* color 3)) light))))
         (green (plus-linear (min 63 (* (ref gamepal (+ (* color 3) 1)) light))))
         (blue (plus-linear (min 63 (* (ref gamepal (+ (* color 3) 2)) light))))
         (luminance (+ (* 0.2126 red) (* 0.7152 green) (* 0.0722 blue)))
         (lightness (if (<= luminance (/ 216 24389))
                        (* luminance (/ 24389 27))
                        (- (* 116 (expt luminance (/ 1 3))) 16)))
         (step (min PLUS_AO_STEP (/ lightness 6)))
         (target (- lightness (* (- PLUS_AO_RANGE row) step)))
         (level (if (<= target 8)
                    (* target (/ 27 24389))
                    (expt (/ (+ target 16) 116) 3)))
         (factor (if (= luminance 0) 0 (/ level luminance))))
    (vector (plus-channel (* red factor))
            (plus-channel (* green factor))
            (plus-channel (* blue factor)))))

(define (plus-palette-error target index)
  (let ((red (- (ref target 0) (ref gamepal (* index 3))))
        (green (- (ref target 1) (ref gamepal (+ (* index 3) 1))))
        (blue (- (ref target 2) (ref gamepal (+ (* index 3) 2)))))
    (+ (* red red) (* green green) (* blue blue))))

(define (plus-build-ao-palette)
  (let* ((count (* (+ (vector-length vgaCeiling) 1) PLUS_AO_RANGE 5))
         (targets (make-vector count 0))
         (errors (make-vector count 0))
         (reserved (make-bytevector 256 0)))
    (let slots ((slot 0))
      (when (< slot (vector-length plus-palette-slots))
        (setf! reserved (ref plus-palette-slots slot) 1)
        (slots (+ slot 1))))
    (let colors ((index 0))
      (when (< index count)
        (let* ((row (remainder index PLUS_AO_RANGE))
               (light (remainder (quotient index PLUS_AO_RANGE) 5))
               (surface (quotient index (* PLUS_AO_RANGE 5)))
               (color (if (= surface 0) FLOOR (ref vgaCeiling (- surface 1))))
               (factor (/ (+ 15 (* light 2)) 15))
               (target (plus-ao-target color factor row)))
          (setf! targets index target)
          (setf! errors index
                 (let search ((color 0) (best (+ (* 3 63 63) 1)))
                   (if (= color 256)
                       best
                       (search (+ color 1)
                               (if (= (ref reserved color) 1)
                                   best
                                   (min best (plus-palette-error target color))))))))
        (colors (+ index 1))))
    (let slots ((slot 0))
      (when (< slot (vector-length plus-palette-slots))
        (let* ((best (if (< slot PLUS_AO_RANGE)
                         slot
                         (let search ((index 1) (best 0))
                           (if (= index count)
                               best
                               (search (+ index 1) (if (> (ref errors index) (ref errors best)) index best))))))
               (target (ref targets best))
               (color (ref plus-palette-slots slot)))
          (let channels ((channel 0))
            (when (< channel 3)
              (setf! gamepal (+ (* color 3) channel) (ref target channel))
              (channels (+ channel 1))))
          (let update ((index 0))
            (when (< index count)
              (setf! errors index (min (ref errors index) (plus-palette-error (ref targets index) color)))
              (update (+ index 1)))))
        (slots (+ slot 1))))))

(define (plus-build-ao-colors row)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (let ((target (plus-ao-target color 1 row)))
          (setf! table color
                 (let search ((index 1) (best 0))
                   (if (= index 256)
                       best
                       (search (+ index 1)
                               (if (< (plus-palette-error target index) (plus-palette-error target best))
                                   index best))))))
        (colors (+ color 1))))
    table))

(define (plus-build-ao-shades row)
  (let ((dark (plus-build-ao-colors row))
        (debug-color
         (let ((target (ref plus-ao-debug-colors (max row 0))))
           (let search ((color 1) (best 0))
             (if (= color 256)
                 best
                 (search (+ color 1)
                         (if (< (plus-palette-error target color) (plus-palette-error target best))
                             color best))))))
        (shades (make-vector 20 0)))
    (let levels ((level 0))
      (when (< level 20)
        (let ((table (make-bytevector 256 0))
              (lit (ref plus-shades level)))
          (let colors ((color 0))
            (when (< color 256)
              (setf! table color (if plus-ao-debug debug-color (ref dark (ref lit color))))
              (colors (+ color 1))))
          (setf! shades level table))
        (levels (+ level 1))))
    shades))

(define (plus-build-ao)
  (let rows ((row 0))
    (when (< row PLUS_AO_RANGE)
      (setf! plus-ao-shades row (plus-build-ao-shades row))
      (setf! plus-corner-shades row (plus-build-ao-shades (- row PLUS_CORNER_STEPS)))
      (rows (+ row 1)))))

(define (plus-build-shades)
  (when plus-enabled (plus-build-ao-palette))
  (let ((identity (make-bytevector 256 0)))
    (let loop ((index 0))
      (when (< index 256)
        (let ((luma (truncate (/ (+ (* 54 (ref gamepal (* index 3)))
                                      (* 183 (ref gamepal (+ (* index 3) 1)))
                                      (* 19 (ref gamepal (+ (* index 3) 2))))
                                   256))))
          (setf! identity index index)
          (setf! plus-luma index luma)
          (setf! plus-emissive index (if (>= luma PLUS_EMISSIVE_LUMA) 1 0)))
        (loop (+ index 1))))
    (setf! plus-shades 4 identity))
  (let bright ((level 1))
    (when (<= level 4)
      (setf! plus-shades (- 4 level) (plus-build-table (+ 15 (* level 2))))
      (bright (+ level 1))))
  (let dark ((level 1))
    (when (< level 16)
      (setf! plus-shades (+ level 4) (plus-build-table (- 15 level)))
      (dark (+ level 1))))
  (plus-build-ao))

(define (plus-light-passable? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE) (< (tileat tilex tiley) 128)))

(define (plus-box-distance worldx worldy left top right bottom)
  (let ((dx (max 0 (- left worldx) (- worldx right)))
        (dy (max 0 (- top worldy) (- worldy bottom))))
    (+ (* dx dx) (* dy dy))))

(define (plus-wall-distance worldx worldy tilex tiley)
  (let ((tile (tileat tilex tiley))
        (limit (* PLUS_AO_WIDTH PLUS_AO_WIDTH)))
    (cond
      ((= tile 0) limit)
      ((and (> pwallstate 0)
            (or (and (= tilex pwallx) (= tiley pwally))
                (and (= tilex (+ pwallx (dir-dx pwalldir)))
                     (= tiley (+ pwally (dir-dy pwalldir))))))
       (let ((left (+ (* pwallx TILEGLOBAL) (* pwallpos 1024 (dir-dx pwalldir))))
             (top (+ (* pwally TILEGLOBAL) (* pwallpos 1024 (dir-dy pwalldir)))))
         (plus-box-distance worldx worldy left top (+ left TILEGLOBAL) (+ top TILEGLOBAL))))
      ((and (>= tile 128) (< tile 192))
       (let* ((door (bitwise-and tile 127))
              (position (ref doorposition door))
              (left (* tilex TILEGLOBAL))
              (top (* tiley TILEGLOBAL)))
         (if (= position 65535)
             limit
             (if (ref doorvertical door)
                 (plus-box-distance worldx worldy (+ left 32768) (+ top position)
                                    (+ left 32768) (+ top TILEGLOBAL))
                 (plus-box-distance worldx worldy (+ left position) (+ top 32768)
                                    (+ left TILEGLOBAL) (+ top 32768))))))
      (else
       (plus-box-distance worldx worldy (* tilex TILEGLOBAL) (* tiley TILEGLOBAL)
                          (* (+ tilex 1) TILEGLOBAL) (* (+ tiley 1) TILEGLOBAL))))))

(define (plus-ao-distance worldx worldy)
  (let ((left (max 0 (arithmetic-shift (- worldx PLUS_AO_WIDTH) -16)))
        (right (min (- MAPSIZE 1) (arithmetic-shift (+ worldx PLUS_AO_WIDTH) -16)))
        (top (max 0 (arithmetic-shift (- worldy PLUS_AO_WIDTH) -16)))
        (bottom (min (- MAPSIZE 1) (arithmetic-shift (+ worldy PLUS_AO_WIDTH) -16))))
    (let columns ((tilex left) (distance (* PLUS_AO_WIDTH PLUS_AO_WIDTH)))
      (if (or (> tilex right) (= distance 0))
          distance
          (columns (+ tilex 1)
                   (let rows ((tiley top) (nearest distance))
                     (if (or (> tiley bottom) (= nearest 0))
                         nearest
                         (rows (+ tiley 1)
                               (min nearest (plus-wall-distance worldx worldy tilex tiley))))))))))

(define (plus-corner-wall? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
       (let ((tile (tileat tilex tiley)))
         (and (> tile 0) (< tile 128)))
       (not (and (> pwallstate 0)
                 (= tilex (+ pwallx (dir-dx pwalldir)))
                 (= tiley (+ pwally (dir-dy pwalldir)))))))

(define (plus-corner? worldx worldy)
  (let* ((tilex (arithmetic-shift worldx -16))
         (tiley (arithmetic-shift worldy -16))
         (offsetx (- worldx (* tilex TILEGLOBAL)))
         (offsety (- worldy (* tiley TILEGLOBAL)))
         (dx (min offsetx (- TILEGLOBAL offsetx)))
         (dy (min offsety (- TILEGLOBAL offsety))))
    (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
         (>= dx 0) (< dx PLUS_AO_WIDTH) (>= dy 0) (< dy PLUS_AO_WIDTH)
         (< (+ (* dx dx) (* dy dy)) (* PLUS_AO_WIDTH PLUS_AO_WIDTH))
         (= (tileat tilex tiley) 0)
         (plus-corner-wall? (+ tilex (if (< offsetx (/ TILEGLOBAL 2)) -1 1)) tiley)
         (plus-corner-wall? tilex (+ tiley (if (< offsety (/ TILEGLOBAL 2)) -1 1))))))

(define (plus-ao level16 worldx worldy edge)
  (let ((shade (if plus-enabled (+ (plus-shade level16) 4) 4)))
    (if (and plus-enabled plus-ao-enabled)
        (let ((distance (* (plus-ao-distance worldx worldy) PLUS_AO_RANGE PLUS_AO_RANGE))
              (width (* PLUS_AO_WIDTH PLUS_AO_WIDTH)))
          (let bands ((band 0))
            (cond ((= band PLUS_AO_RANGE)
                   (if (and plus-contact-enabled edge)
                       (ref (ref plus-ao-shades (- PLUS_AO_RANGE 1)) shade)
                       (ref plus-shades shade)))
                  ((< distance (* width (+ band 1) (+ band 1)))
                   (if (and plus-corners-enabled (plus-corner? worldx worldy))
                       (ref (ref plus-corner-shades band) shade)
                       (ref (ref plus-ao-shades band) shade)))
                  (else (bands (+ band 1))))))
        (ref plus-shades shade))))

(define (plus-check-keys)
  (when plus-enabled
    (let* ((shift (or (ref Keyboard sc_LShift) (ref Keyboard sc_RShift)))
           (ao (and shift (ref Keyboard sc_P)))
           (corners (and shift (ref Keyboard sc_O)))
           (contact (and shift (ref Keyboard sc_I))))
      (when (and ao (not plus-ao-key))
        (set! plus-ao-enabled (not plus-ao-enabled)))
      (when (and corners (not plus-corners-key))
        (set! plus-corners-enabled (not plus-corners-enabled)))
      (when (and contact (not plus-contact-key))
        (set! plus-contact-enabled (not plus-contact-enabled)))
      (set! plus-ao-key ao)
      (set! plus-corners-key corners)
      (set! plus-contact-key contact))))

(define (plus-spread-light target lightx lighty radius levels)
  (let ((queue (make-vector (* MAPSIZE MAPSIZE) 0))
        (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
        (tail 1))
    (setf! queue 0 (plus-light-index lightx lighty))
    (setf! distance (plus-light-index lightx lighty) 0)
    (let flood ((head 0))
      (when (< head tail)
        (let* ((spot (ref queue head))
               (tilex (remainder spot MAPSIZE))
               (tiley (quotient spot MAPSIZE))
               (steps (ref distance spot))
               (level (- levels (truncate (/ (* levels steps) radius)))))
          (when (> level (ref target spot))
            (setf! target spot level))
          (when (< steps radius)
            (let visit ((neighbors (list (tuple (- tilex 1) tiley) (tuple (+ tilex 1) tiley)
                                          (tuple tilex (- tiley 1)) (tuple tilex (+ tiley 1)))))
              (when (pair? neighbors)
                (let* ((neighbor (car neighbors))
                       (nextx (ref neighbor 0))
                       (nexty (ref neighbor 1)))
                  (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE))
                    (let ((next (plus-light-index nextx nexty)))
                      (let ((nextlevel (- levels (truncate (/ (* levels (+ steps 1)) radius)))))
                        (when (> nextlevel (ref target next))
                          (setf! target next nextlevel)))
                      (when (and (< (tileat nextx nexty) 128)
                                 (> (ref distance next) (+ steps 1)))
                        (setf! distance next (+ steps 1))
                        (setf! queue tail next)
                        (set! tail (+ tail 1)))))
                  (visit (cdr neighbors)))))
          (flood (+ head 1))))))))

(define (plus-build-lights)
  (let clear ((index 0))
    (when (< index (* MAPSIZE MAPSIZE))
      (setf! plus-lightmap index 0)
      (clear (+ index 1))))
  (let lights ((index 0))
    (when (< index statcount)
      (when (plus-light-shape? (ref stat-shape index))
        (plus-spread-light plus-lightmap (ref stat-tilex index) (ref stat-tiley index)
                           PLUS_LIGHT_RADIUS PLUS_LIGHT_LEVELS))
      (lights (+ index 1)))))

(define (plus-flash-at tilex tiley)
  (when plus-enabled
    (let ((flashmap (ref plus-flashmaps plus-flash-next))
          (queue (make-vector (* MAPSIZE MAPSIZE) 0))
          (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
          (tail 1))
      (let clear ((index 0))
        (when (< index (* MAPSIZE MAPSIZE))
          (setf! flashmap index 0)
          (clear (+ index 1))))
      (setf! queue 0 (plus-light-index tilex tiley))
      (setf! distance (plus-light-index tilex tiley) 0)
      (let flood ((head 0) (maxd 0))
        (if (< head tail)
            (let* ((spot (ref queue head))
                   (tx (remainder spot MAPSIZE))
                   (ty (quotient spot MAPSIZE))
                   (steps (ref distance spot)))
              (let visit ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                           (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                (when (pair? neighbors)
                  (let* ((neighbor (car neighbors))
                         (nextx (ref neighbor 0))
                         (nexty (ref neighbor 1)))
                    (when (plus-light-passable? nextx nexty)
                      (let ((next (plus-light-index nextx nexty)))
                        (when (> (ref distance next) (+ steps 1))
                          (setf! distance next (+ steps 1))
                          (setf! queue tail next)
                          (set! tail (+ tail 1)))))
                    (visit (cdr neighbors)))))
              (flood (+ head 1) (max maxd steps)))
            (let stamp ((index 0))
              (if (< index tail)
                  (let* ((spot (ref queue index))
                         (tx (remainder spot MAPSIZE))
                         (ty (quotient spot MAPSIZE))
                         (steps (ref distance spot))
                         (level (if (= maxd 0)
                                    PLUS_FLASH_LEVELS
                                    (max 1 (- PLUS_FLASH_LEVELS
                                              (truncate (/ (* PLUS_FLASH_LEVELS steps) maxd)))))))
                    (setf! flashmap spot level)
                    (let walls ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                                 (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                      (when (pair? neighbors)
                        (let* ((neighbor (car neighbors))
                               (nextx (ref neighbor 0))
                               (nexty (ref neighbor 1)))
                          (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE)
                                     (>= (tileat nextx nexty) 128))
                            (let ((next (plus-light-index nextx nexty)))
                              (when (> level (ref flashmap next))
                                (setf! flashmap next level)))))
                        (walls (cdr neighbors))))
                    (stamp (+ index 1)))
                  (begin
                    (setf! plus-flash-starts plus-flash-next TimeCount)
                    (set! plus-flash-next (remainder (+ plus-flash-next 1) PLUS_FLASH_COUNT))))))))))

(define (plus-guard? shape)
  (or (and (>= shape SPR_GRD_S_1) (< shape SPR_GRD_DIE_1))
      (= shape SPR_GRD_PAIN_2)
      (and (>= shape SPR_GRD_SHOOT1) (<= shape SPR_GRD_SHOOT3))))

(define (plus-build-feet)
  (let shapes ((shape SPR_GRD_S_1))
    (when (<= shape SPR_GRD_SHOOT3)
      (when (plus-guard? shape)
        (let* ((page (PM_GetPage (+ PMSpriteStart shape)))
               (left (readu16 page 0))
               (right (readu16 page 2))
               (first 64)
               (last -1))
          (let columns ((column left))
            (when (<= column right)
              (let posts ((offset (readu16 page (+ 4 (* (- column left) 2)))))
                (let ((end (readu16 page offset)))
                  (when (> end 0)
                    (when (and (> end 120) (< (readu16 page (+ offset 4)) 128))
                      (set! first (min first column))
                      (set! last (max last column)))
                    (posts (+ offset 6)))))
              (columns (+ column 1))))
          (when (<= first last)
            (setf! plus-feet shape (tuple first (+ last 1))))))
      (shapes (+ shape 1)))))

(define (plus-shadow index feet)
  (let* ((height (ref vis-height index))
         (scale (truncate (/ height 8))))
    (when (and (> scale 0) (<= scale maxscale))
      (let* ((rows (* scale 2))
             (center (ref vis-x index))
             (left (+ center (- (truncate (/ (* (- (ref feet 0) 1) rows) 64)) scale)))
             (right (+ center (- (truncate (/ (* (+ (ref feet 1) 1) rows) 64)) scale)))
             (bottom (+ (truncate (/ (- viewheight rows) 2)) rows -1))
             (depth (max 1 (truncate (/ rows 64))))
             (level (plus-light-level 0 (ref vis-tilex index) (ref vis-tiley index)))
             (color (plus-color FLOOR (plus-shade (min 240 (+ level PLUS_SHADOW_DEPTH)))))
             (luma (ref plus-luma color)))
        (let scan ((row (max (arithmetic-shift viewheight -1) (- bottom depth))))
          (when (and (< row (+ bottom depth)) (< row viewheight))
            (let* ((inset (truncate (/ (* (- right left) (abs (- row bottom))) (* depth 4))))
                   (end (min viewwidth (- right inset))))
              (let columns ((column (max 0 (+ left inset))))
                (when (< column end)
                  (when (and (< (ref wallheight column) height)
                             (>= row (+ (arithmetic-shift viewheight -1) (ref plus-boundaries column))))
                    (let ((pixel (+ (* (+ viewtop row) screenwidth) viewleft column)))
                      (when (> (ref plus-luma (ref framebuffer pixel)) luma)
                        (setf! framebuffer pixel color))))
                  (columns (+ column 1)))))
            (scan (+ row 1))))))))

(define (plus-draw-shadows)
  (when plus-enabled
    (let sprites ((index 0))
      (when (< index viscount)
        (let ((shape (ref vis-shape index)))
          (when (plus-guard? shape)
            (let ((feet (ref plus-feet shape)))
              (when feet (plus-shadow index feet)))))
        (sprites (+ index 1))))))

(define (plus-palette-loaded)
  (when plus-enabled (plus-build-shades)))

(define (plus-startup)
  (when plus-enabled (plus-build-feet)))

(define (plus-level-loaded)
  (when plus-enabled
    (let reset ((slot 0))
      (when (< slot PLUS_FLASH_COUNT)
        (let ((flashmap (ref plus-flashmaps slot)))
          (let clear ((index 0))
            (when (< index (* MAPSIZE MAPSIZE))
              (setf! flashmap index 0)
              (clear (+ index 1)))))
        (setf! plus-flash-starts slot -1)
        (reset (+ slot 1))))
    (set! plus-flash-next 0)
    (plus-build-lights)))

(define (plus-build-planes)
  (let columns ((column 0))
    (when (< column viewwidth)
      (let ((boundary (arithmetic-shift (scale-rows (ref wallheight column)) -1)))
        (setf! plus-boundaries column boundary)
        (setf! plus-planex column (* (- (ref wallx column) viewx) boundary))
        (setf! plus-planey column (* (- (ref wally column) viewy) boundary)))
      (columns (+ column 1)))))

(define (plus-draw-planes)
  (when plus-enabled
    (plus-build-planes)
    (let ((halfh (arithmetic-shift viewheight -1))
          (ceilcolor (ceiling-color)))
      (let rows ((height 1))
        (when (< height halfh)
          (let ((projection (/ 1 (+ height 0.5)))
                (top (- halfh 1 height))
                (bottom (+ halfh height)))
            (let columns ((column 0))
              (when (< column viewwidth)
                (when (>= height (ref plus-boundaries column))
                  (let* ((worldx (+ viewx (* (ref plus-planex column) projection)))
                         (worldy (+ viewy (* (ref plus-planey column) projection)))
                         (shade (plus-ao (plus-light-level 0
                                                           (bitwise-and (arithmetic-shift worldx -16) 63)
                                                           (bitwise-and (arithmetic-shift worldy -16) 63))
                                         worldx worldy (= height (ref plus-boundaries column)))))
                    (setf! framebuffer (+ (* (+ viewtop top) screenwidth) viewleft column)
                           (ref shade ceilcolor))
                    (setf! framebuffer (+ (* (+ viewtop bottom) screenwidth) viewleft column)
                           (ref shade FLOOR))))
                (columns (+ column 1)))))
          (rows (+ height 1)))))))

(define (plus-door-edge column height)
  (when (and plus-enabled plus-ao-enabled)
    (let* ((rows (scale-rows height))
           (top (truncate (/ (- viewheight rows) 2)))
           (start (max top 0))
           (end (min viewheight (+ top (quotient (+ rows 63) 64)))))
      (when (and (>= rows 4) (< start end))
        (let* ((pixel (+ (* (+ viewtop start) screenwidth) viewleft column))
               (color (ref framebuffer pixel))
               (shade (plus-color color 3)))
          (when (< (ref plus-luma shade) (ref plus-luma color))
            (let pixels ((row start) (pixel pixel))
              (when (< row end)
                (setf! framebuffer pixel shade)
                (pixels (+ row 1) (+ pixel screenwidth))))))))))
